# Generated by Django 4.2.7 on 2023-12-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название сплитов')),
            ],
            options={
                'verbose_name': 'Сплит',
                'verbose_name_plural': 'Сплиты',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название упражнения')),
                ('content', models.TextField(verbose_name='Краткое описание упражнения')),
                ('content_full', models.TextField(verbose_name='Полное описание упражнения')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Первое фото')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Второе фото')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Третье фото')),
                ('created_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gumfuel.category', verbose_name='Категория сплита')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
    ]
