# Generated by Django 4.2.7 on 2023-12-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumfuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='link_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка видео'),
        ),
    ]
