# Generated by Django 4.2.7 on 2023-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumfuel', '0002_exercise_link_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название части тела')),
            ],
            options={
                'verbose_name': 'Часть',
                'verbose_name_plural': 'Частей',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='titles',
            field=models.ManyToManyField(to='gumfuel.bodypart'),
        ),
    ]
