# Generated by Django 4.2.7 on 2023-12-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumfuel', '0005_rename_titles_exercise_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodypart',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bodypart',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название части тела'),
        ),
    ]
