# Generated by Django 4.2.7 on 2023-12-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gumfuel', '0006_bodypart_slug_alter_bodypart_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodypart',
            old_name='title',
            new_name='tag',
        ),
    ]
