# Generated by Django 5.0 on 2024-01-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gumfuel', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='tag',
        ),
        migrations.DeleteModel(
            name='BodyPart',
        ),
    ]
